### ISSUE TITLE
There's tow issues when I run on my device

### ISSUE THREAD

**Issue by Davidleeeeee** [acton393/WeexSwiftSample#1]
Xcode 7.3.1, iphone6s plus
![image](https://cloud.githubusercontent.com/assets/10355435/17656807/ab88d330-62f0-11e6-965d-29ab9afa3d4f.png)
![image](https://cloud.githubusercontent.com/assets/10355435/17656815/c098c1fe-62f0-11e6-968a-7530d322315f.png)

**Comment by acton393** [comment]
hi @Davidleeeeee  这个问题我注意到了，会尽快想解决方法，

主要问题是: 使用了 C 的库， swift 编译报错

**Comment by pythons** [comment]
已收到，会尽快发个 PR fix.

**Comment by acton393** [comment]
hi  @Davidleeeeee  
[pr](https://github.com/alibaba/weex/pull/998)  稍后会merge， 试下，如有问题继续提
