### ISSUE TITLE
weexsdk0.9.5.3不存在啊

### ISSUE THREAD

**Issue by SeongBrave** [acton393/WeexSwiftSample#3]
WeexSDK (0.9.5.1)
Versions: 0.9.5.1, 0.9.5, 0.9.4, 0.8.0, 0.7.0, 0.6.1, 0.6.0 [master repo]

**Comment by acton393** [comment]
hi @SeongBrave  尝试 `pod repo update` 更新一下本地仓库，再`install` 

远端可以在这边查看 [cocoaPods 仓库](https://github.com/CocoaPods/Specs/tree/12368b9dc427542381eb2d7372e6b78be01a55ca/Specs/7/2/9/WeexSDK)

**Comment by SeongBrave** [comment]
恩恩，是这个原因，多谢了
