### ISSUE TITLE
[!] Unable to satisfy the following requirements:

### ISSUE THREAD

**Issue by mario-huang** [acton393/WeexSwiftSample#4]
[!] Unable to satisfy the following requirements:

- `WeexSDK (= 0.10.2)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `WeexSDK (= 0.10.2)`.

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

**Comment by acton393** [comment]
@myeveryheart  maybe check your cocoaPods environment or just run `pod update`
