### ISSUE TITLE
在swift4下，运行后会报module:event doesn't exist

### ISSUE THREAD

**Issue by hodgevk** [acton393/WeexSwiftSample#5]
在swift4下，运行后会报module:event doesn't exist

**Comment by acton393** [comment]
@hodgevk  估计应该是swift 4里面有改了啥编译特性， module 是 swift extension oc的class 实现的， oc 用来exports 方法给JS

**Comment by acton393** [comment]
@hodgevk  swift4 强制增加 @objc 属性， https://stackoverflow.com/questions/27097688/can-objective-c-code-call-swift-extension-on-class
