### ISSUE TITLE
swift如何调用component的方法

### ISSUE THREAD

**Issue by hanlike** [acton393/WeexSwiftSample#6]
想问问 
swift组件怎么让weex下调用其方法呢
oc写法是成功的
swift 参考module写法 还是 is not function

**Comment by acton393** [comment]
参考module 写法应该是OK的，之后有空时候可以增加个case

**Comment by acton393** [comment]
@thecorsair 
 https://github.com/acton393/WeexSwiftSample/commit/6fe5a37c376d4000e9f1f76a59cdaf67f07ad8ca   注意 必须添加 在swift 4 必须添加 @objc， 不然有可能调用不到
